name: Go

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
